name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout the default branch
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 7.x.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal
        
      - name: Publish AutoMoxture.NUnit
        run: dotnet nuget push AutoMoxture.NUnit/bin/Release/*.nupkg -s https://nuget.pkg.github.com/s8Usy429/index.json -k ${{secrets.GITHUB_TOKEN}}

      - name: Publish AutoMoxture.XUnit
        run: dotnet nuget push AutoMoxture.XUnit/bin/Release/*.nupkg -s https://nuget.pkg.github.com/s8Usy429/index.json -k ${{secrets.GITHUB_TOKEN}}

      - name: Publish AutoMoxture.NUnit (nuget.org)
        run: dotnet nuget push AutoMoxture.NUnit/bin/Release/*.nupkg -s 'https://api.nuget.org/v3/index.json' -k ${{secrets.NUGET_API_KEY}}

      - name: Publish AutoMoxture.XUnit (nuget.org)
        run: dotnet nuget push AutoMoxture.XUnit/bin/Release/*.nupkg -s 'https://api.nuget.org/v3/index.json' -k ${{secrets.NUGET_API_KEY}}
